name: medai
description: Med AI is a free chatbot app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  animated_segmented_tab_control: ^1.0.1
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.6.14
  flutter_tts: ^3.6.3
  fluttertoast: ^8.2.1
  get: ^4.6.5
  google_fonts: ^4.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.3.2
  read_pdf_text: ^0.2.1
  speech_to_text: ^6.1.1

  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: ""
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
